### ISSUE TITLE
old version do not work 

### ISSUE THREAD

**Issue by RoxxorXx** [hrai/auto-save-vs-extension#31] opened 2021-12-30 22:09 UTC
I tried to use this "old" version on my vs 2019 but it seems not working as excpected.. Nothings is save, nothing appear on tools options. 

Also report in q&a; an other one is in the same situation.

**Comment by hrai** [comment] 2022-01-10 00:02
It seems to work fine for me so I can't replicate it. 

Can you try uninstalling and reinstalling again?

**Comment by RoxxorXx** [comment] 2022-01-11 10:23
Allready try that, three times. 
Btw, i'm under windows 11 maybe that's a part of the problem ? 
also i'm using resharper. (but this seems not to be a part of the issue)

**Comment by RoxxorXx** [comment] 2022-01-19 09:30
okey, i'm back with more informations; i reinstalled it on an other compouter that run windows 10 and the last current version of vs 2019 (16.11.9). The extension do not work. So, I don't know what can cause that..

**Comment by ChristianMay21** [comment] 2022-01-26 18:09
Also not working for me unfortunately - fresh install of VS 2019 on Windows 10.  The configuration options are also not appearing in Tools > Options.

**Comment by ChristianMay21** [comment] 2022-01-26 18:34
It would also appear from the comments on the extension page that there is a third person experiencing this issue (@RoxxorXx  seems to be there as well)
![image](https://user-images.githubusercontent.com/45889402/151225094-c199e523-5bbf-4e0e-b651-fab5bda35b6f.png)

**Comment by hrai** [comment] 2022-02-01 03:17
Hi all @ChristianMay21 @RoxxorXx , 

I ended up creating a new repo for the 2019 version. Here's the repo. https://github.com/hrai/auto-save-vs-extension-2019/

Also, the bug should now be fixed in the latest 3.1 version. If it persists, feel free to open a new issue in the above repo.

Apologies for the confusion.

**Closed by hrai** 2022-02-01 03:17 UTC

**Comment by ChristianMay21** [comment] 2022-02-01 13:20
Hi @hrai - thanks so much for the fix. There's been many a time I thought my code wasn't working just because I forgot to hit save, and your extension has saved me from that silly mistake many times - thanks for all the work you put in to it.

I have updated my extension and can confirm that it is now functioning as intended, including the configuration options. Thanks so much again, and happy coding.
